name: Generate Gallery

on:
  push:
    branches: [main]
    paths: ["photos/**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: mkdir -p index && cd scripts && go run indexer.go
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate gallery files"
          file_pattern: index/*.json
